const data = [
  { title: "🔎GETTING STARTED", link: "/doc#top" },
  { title: "🪜STRUCTURE", link: "/doc#structure" },
  { title: "❓QUERIES", link: "/doc#queries" },
  { title: "📝FAQ", link: "/doc#FAQ" },
  { title: "🎉THANK YOU", link: "/doc#thankyou" },
  { title: "🥊 Try UltimateAPI", link: "/doc#getting-started-try" },
  { title: "🔑 Generate the key", link: "/doc#getting-started-generate" },
  { title: "🥇 Your first request", link: "/doc#getting-started-your" },
  { title: "🎫 ID", link: "/doc#structure-id" },
  { title: "✒️ Name", link: "/doc#structure-name" },
  { title: "📊 Stats", link: "/doc#structure-stats" },
  { title: "🏆 Record", link: "/doc#structure-record" },
  { title: "🥷 Find a fighter", link: "/doc#queries-fighter" },
  { title: "🕵️ Find by attributes", link: "/doc#queries-attributes" },
  { title: "📏 Height", link: "/doc#queries-height" },
  { title: "⚖️ Weight", link: "/doc#queries-weight" },
  { title: "🥋 Stance", link: "/doc#queries-stance" },
  { title: "🏅 Record", link: "/doc#queries-rec" },
  { title: "🆔 Find the ID", link: "/doc#queries-find" },
  { title: "🔍 Search with ID", link: "/doc#queries-search" },
  { title: "📀 How did you get the data?", link: "/doc#FAQ-data" },
  { title: "⁉️ Why is the data formatted so weird?", link: "/doc#FAQ-weird" },
  { title: "⏰ How often will this API be updated?", link: "/doc#FAQ-updated" },
  {
    title: "☝️ I'm confused is this a solo project?",
    link: "/doc#FAQ-project",
  },
  { title: "🙃 Are these real questions?", link: "/doc#FAQ-questions" },
];

module.exports = data;
