const data = [
  "🔎GETTING STARTED",
  "🪜STRUCTURE",
  "❓QUERIES",
  "📝FAQ",
  "🎉THANK YOU",
  "🥊 Try UltimateAPI",
  "🔑 Generate the key",
  "🥇 Your first request",
  "🎫 ID",
  "✒️ Name",
  "📊 Stats",
  "🏆 Record",
  "🥷 Find a fighter",
  "🕵️ Find by attributes",
  "📏 Height",
  "⚖️ Weight",
  "🥋 Stance",
  "🏅 Record",
  "🆔 Find the ID",
  "🔍 Search with ID",
  "📀 How did you get the data?",
  "⁉️ Why is the data formatted so weird?",
  "⏰ How often will this API be updated?",
  "☝️ I'm confused is this a solo project?",
  "🙃 Are these real questions?",
];

module.exports = data;
